const db = {
    "drivers": [
        { "name": "Max Verstappen", "team": "Red Bull Racing", "points": 460 },
        { "name": "Sergio Pérez", "team": "Red Bull Racing", "points": 285 },
        { "name": "Lewis Hamilton", "team": "Mercedes-AMG", "points": 380 },
        { "name": "George Russell", "team": "Mercedes-AMG", "points": 295 },
        { "name": "Charles Leclerc", "team": "Scuderia Ferrari", "points": 360 },
        { "name": "Carlos Sainz", "team": "Scuderia Ferrari", "points": 290 },
        { "name": "Lando Norris", "team": "McLaren", "points": 270 },
        { "name": "Oscar Piastri", "team": "McLaren", "points": 185 },
        { "name": "Fernando Alonso", "team": "Aston Martin", "points": 220 },
        { "name": "Lance Stroll", "team": "Aston Martin", "points": 145 },
        { "name": "Pierre Gasly", "team": "Alpine", "points": 160 },
        { "name": "Esteban Ocon", "team": "Alpine", "points": 140 },
        { "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 95 },
        { "name": "Zhou Guanyu", "team": "Kick Sauber", "points": 45 },
        { "name": "Yuki Tsunoda", "team": "RB", "points": 75 },
        { "name": "Daniel Ricciardo", "team": "RB", "points": 60 },
        { "name": "Alex Albon", "team": "Williams", "points": 55 },
        { "name": "Logan Sargeant", "team": "Williams", "points": 25 },
        { "name": "Kevin Magnussen", "team": "Haas", "points": 40 },
        { "name": "Nico Hulkenberg", "team": "Haas", "points": 35 }
    ],
    "camp1": [
        { "r": 1, "track": "Austrália", "date": "09/03", "type": "Oficial" },
        { "r": 2, "track": "China", "date": "16/03", "type": "Oficial" },
        { "r": 3, "track": "EUA - Austin", "date": "23/03", "type": "Extra" },
        { "r": 4, "track": "Japão", "date": "30/03", "type": "Oficial" },
        { "r": 5, "track": "Bahrein", "date": "13/04", "type": "Oficial" },
        { "r": 6, "track": "Arábia Saudita", "date": "20/04", "type": "Oficial" },
        { "r": 7, "track": "Las Vegas", "date": "27/04", "type": "Extra" },
        { "r": 8, "track": "Miami", "date": "04/05", "type": "Oficial" },
        { "r": 9, "track": "Brasil", "date": "11/05", "type": "Extra" },
        { "r": 10, "track": "Itália - Monza", "date": "18/05", "type": "Extra" },
        { "r": 11, "track": "Canadá", "date": "25/05", "type": "Oficial" },
        { "r": 12, "track": "Mônaco", "date": "01/06", "type": "Oficial" }
    ],
    "camp2": [
        { "r": 1, "track": "Espanha", "date": "15/06", "type": "Oficial" },
        { "r": 2, "track": "Japão", "date": "22/06", "type": "Extra" },
        { "r": 3, "track": "Áustria", "date": "29/06", "type": "Oficial" },
        { "r": 4, "track": "Grã-Bretanha", "date": "06/07", "type": "Oficial" },
        { "r": 5, "track": "Itália - Imola", "date": "13/07", "type": "Extra" },
        { "r": 6, "track": "Bélgica", "date": "20/07", "type": "Oficial" },
        { "r": 7, "track": "Hungria", "date": "27/07", "type": "Oficial" },
        { "r": 8, "track": "Bahrein", "date": "10/08", "type": "Extra" },
        { "r": 9, "track": "Países Baixos", "date": "24/08", "type": "Oficial" },
        { "r": 10, "track": "Canadá", "date": "31/08", "type": "Extra" },
        { "r": 11, "track": "Itália - Monza", "date": "07/09", "type": "Oficial" },
        { "r": 12, "track": "Brasil", "date": "14/09", "type": "Oficial" }
    ],
    "camp3": [
        { "r": 1, "track": "Azerbaijão", "date": "28/09", "type": "Oficial" },
        { "r": 2, "track": "Bélgica", "date": "05/10", "type": "Extra" },
        { "r": 3, "track": "Cingapura", "date": "12/10", "type": "Oficial" },
        { "r": 4, "track": "Áustria", "date": "19/10", "type": "Extra" },
        { "r": 5, "track": "EUA - Austin", "date": "26/10", "type": "Oficial" },
        { "r": 6, "track": "México", "date": "02/11", "type": "Oficial" },
        { "r": 7, "track": "Brasil", "date": "09/11", "type": "Oficial" },
        { "r": 8, "track": "Arábia Saudita", "date": "16/11", "type": "Extra" },
        { "r": 9, "track": "Las Vegas", "date": "22/11", "type": "Oficial" },
        { "r": 10, "track": "Qatar", "date": "30/11", "type": "Oficial" },
        { "r": 11, "track": "Grã-Bretanha", "date": "07/09", "type": "Extra" },
        { "r": 12, "track": "Abu Dhabi", "date": "14/12", "type": "Oficial" }
    ]
};
