name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Neocities
      uses: bcomnes/neocities-action@v2
      with:
        api_key: ${{ secrets.NEOCITIES_API_KEY }}
        cleanup: false
